In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("/Users/aryangalande/Desktop/LP3 AG/ASGMT08-NeuralNetwork/Churn_Modelling.csv")

In [4]:
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [5]:
df.isnull()

RowNumber  CustomerId  Surname  CreditScore  Geography  Gender    Age  \
0         False       False    False        False      False   False  False   
1         False       False    False        False      False   False  False   
2         False       False    False        False      False   False  False   
3         False       False    False        False      False   False  False   
4         False       False    False        False      False   False  False   
...         ...         ...      ...          ...        ...     ...    ...   
9995      False       False    False        False      False   False  False   
9996      False       False    False        False      False   False  False   
9997      False       False    False        False      False   False  False   
9998      False       False    False        False      False   False  False   
9999      False       False    False        False      False   False  False   

      Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0      False    False          False      False           False   
1      False    False          False      False           False   
2      False    False          False      False           False   
3      False    False          False      False           False   
4      False    False          False      False           False   
...      ...      ...            ...        ...             ...   
9995   False    False          False      False           False   
9996   False    False          False      False           False   
9997   False    False          False      False           False   
9998   False    False          False      False           False   
9999   False    False          False      False           False   

      EstimatedSalary  Exited  
0               False   False  
1               False   False  
2               False   False  
3               False   False  
4               False   False  
...               ...     ...  
9995            False   False  
9996            False   False  
9997            False   False  
9998            False   False  
9999            False   False  

[10000 rows x 14 columns]

In [6]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [8]:
df.shape

(10000, 14)

In [9]:
df.size

140000

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [11]:
df.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [12]:
df=df.drop(["RowNumber","CustomerId","Surname"],axis=1)

In [13]:
df

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [14]:
df=pd.get_dummies(df,columns=["Geography","Gender"])

In [15]:
df

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0                  1        101348.88       1              True   
1                  1        112542.58       0             False   
2                  0        113931.57       1              True   
3                  0         93826.63       0              True   
4                  1         79084.10       0             False   
...              ...              ...     ...               ...   
9995               0         96270.64       0              True   
9996               1        101699.77       0              True   
9997               1         42085.58       1              True   
9998               0         92888.52       1             False   
9999               0         38190.78       0              True   

      Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0                 False            False           True        False  
1                 False             True           True        False  
2                 False            False           True        False  
3                 False            False           True        False  
4                 False             True           True        False  
...                 ...              ...            ...          ...  
9995              False            False          False         True  
9996              False            False          False         True  
9997              False            False           True        False  
9998               True            False          False         True  
9999              False            False           True        False  

[10000 rows x 14 columns]

In [16]:
df.dtypes

CreditScore            int64
Age                    int64
Tenure                 int64
Balance              float64
NumOfProducts          int64
HasCrCard              int64
IsActiveMember         int64
EstimatedSalary      float64
Exited                 int64
Geography_France        bool
Geography_Germany       bool
Geography_Spain         bool
Gender_Female           bool
Gender_Male             bool
dtype: object

In [17]:
df.columns

Index(['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited', 'Geography_France',
       'Geography_Germany', 'Geography_Spain', 'Gender_Female', 'Gender_Male'],
      dtype='object')

In [18]:
def min_max_normalization(name):
    global df
    df[name]=df[name].astype("float32")
    df[name]=(df[name]-df[name].min())/(df[name].max()-df[name].min())

cols=['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard','EstimatedSalary']
for col in cols:
    min_max_normalization(col)

In [19]:
df

CreditScore       Age  Tenure   Balance  NumOfProducts  HasCrCard  \
0           0.538  0.324324     0.2  0.000000       0.000000        1.0   
1           0.516  0.310811     0.1  0.334031       0.000000        0.0   
2           0.304  0.324324     0.8  0.636357       0.666667        1.0   
3           0.698  0.283784     0.1  0.000000       0.333333        0.0   
4           1.000  0.337838     0.2  0.500246       0.000000        1.0   
...           ...       ...     ...       ...            ...        ...   
9995        0.842  0.283784     0.5  0.000000       0.333333        1.0   
9996        0.332  0.229730     1.0  0.228657       0.000000        1.0   
9997        0.718  0.243243     0.7  0.000000       0.000000        0.0   
9998        0.844  0.324324     0.3  0.299226       0.333333        1.0   
9999        0.884  0.135135     0.4  0.518708       0.000000        1.0   

      IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0                  1         0.506735       1              True   
1                  1         0.562709       0             False   
2                  0         0.569654       1              True   
3                  0         0.469120       0              True   
4                  1         0.395400       0             False   
...              ...              ...     ...               ...   
9995               0         0.481341       0              True   
9996               1         0.508490       0              True   
9997               1         0.210390       1              True   
9998               0         0.464429       1             False   
9999               0         0.190914       0              True   

      Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0                 False            False           True        False  
1                 False             True           True        False  
2                 False            False           True        False  
3                 False            False           True        False  
4                 False             True           True        False  
...                 ...              ...            ...          ...  
9995              False            False          False         True  
9996              False            False          False         True  
9997              False            False           True        False  
9998               True            False          False         True  
9999              False            False           True        False  

[10000 rows x 14 columns]

In [20]:
from sklearn.model_selection import train_test_split
x=df.drop("Exited",axis=1).to_numpy().astype(np.float32)
y=df["Exited"].to_numpy()
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=43)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(7000, 13)
(3000, 13)
(7000,)
(3000,)


In [21]:
x_train

array([[0.206     , 0.27027026, 0.8       , ..., 0.        , 1.        ,
        0.        ],
       [0.806     , 0.3783784 , 0.3       , ..., 0.        , 1.        ,
        0.        ],
       [1.        , 0.35135135, 0.3       , ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.692     , 0.12162162, 0.2       , ..., 0.        , 1.        ,
        0.        ],
       [0.728     , 0.36486486, 0.        , ..., 1.        , 0.        ,
        1.        ],
       [0.546     , 0.2027027 , 0.8       , ..., 0.        , 0.        ,
        1.        ]], dtype=float32)

In [22]:
x_test

array([[0.836     , 0.33783785, 0.2       , ..., 0.        , 1.        ,
        0.        ],
       [0.684     , 0.2027027 , 0.9       , ..., 0.        , 0.        ,
        1.        ],
       [0.666     , 0.7432432 , 0.8       , ..., 0.        , 1.        ,
        0.        ],
       ...,
       [0.772     , 0.14864865, 0.9       , ..., 0.        , 1.        ,
        0.        ],
       [0.806     , 0.1891892 , 0.6       , ..., 0.        , 0.        ,
        1.        ],
       [0.562     , 0.25675675, 0.9       , ..., 0.        , 0.        ,
        1.        ]], dtype=float32)

In [23]:
y_train

array([0, 1, 0, ..., 0, 0, 0])

In [24]:
y_test

array([0, 1, 0, ..., 0, 0, 0])

In [25]:
from keras.models import Sequential
from keras.layers import Dense

model=Sequential()
model.add(Dense(activation="relu", units=6))#input layer
model.add(Dense(activation="relu", units=6))#hidden layer
model.add(Dense(activation="sigmoid", units=1))#output layer
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
model.fit(x_train,y_train,batch_size=10,epochs=50)  
# from keras.models import Sequential
# from keras.layers import Dense

# model=Sequential()
# help("keras.Sequential.compile")
'''
Relu:- Rectified Linear Unit f(x)=max(0,x)
Sigmoid:-  f(x)= 1/(1+e^-x)
'''

Epoch 1/50
700/700 [==============================] - 0s 332us/step - loss: 0.4874 - accuracy: 0.7966
Epoch 2/50
700/700 [==============================] - 0s 323us/step - loss: 0.4605 - accuracy: 0.7977
Epoch 3/50
700/700 [==============================] - 0s 324us/step - loss: 0.4460 - accuracy: 0.8037
Epoch 4/50
700/700 [==============================] - 0s 353us/step - loss: 0.4371 - accuracy: 0.8096
Epoch 5/50
700/700 [==============================] - 0s 326us/step - loss: 0.4327 - accuracy: 0.8144
Epoch 6/50
700/700 [==============================] - 0s 323us/step - loss: 0.4287 - accuracy: 0.8147
Epoch 7/50
700/700 [==============================] - 0s 325us/step - loss: 0.4263 - accuracy: 0.8161
Epoch 8/50
700/700 [==============================] - 0s 326us/step - loss: 0.4247 - accuracy: 0.8167
Epoch 9/50
700/700 [==============================] - 0s 323us/step - loss: 0.4224 - accuracy: 0.8161
Epoch 10/50
700/700 [==============================] - 0s 326us/step - loss: 0.420

'\nRelu:- Rectified Linear Unit f(x)=max(0,x)\nSigmoid:-  f(x)= 1/(1+e^-x)\n'

In [26]:
y_pred=model.predict(x_test)
y_pred=(y_pred>0.5)

94/94 [==============================] - 0s 277us/step


In [27]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))

0.864


In [28]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.87      0.97      0.92      2387
           1       0.81      0.44      0.57       613

    accuracy                           0.86      3000
   macro avg       0.84      0.71      0.74      3000
weighted avg       0.86      0.86      0.85      3000

