In [88]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, classification_report

In [89]:
df=pd.read_csv("/Users/aryangalande/Desktop/LP3 AG/ASGMT07-EmailClassification/emails.csv")

In [90]:
df

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  \
0        Email 1    0   0    1    0    0   0    2    0    0  ...         0   
1        Email 2    8  13   24    6    6   2  102    1   27  ...         0   
2        Email 3    0   0    1    0    0   0    8    0    0  ...         0   
3        Email 4    0   5   22    0    5   1   51    2   10  ...         0   
4        Email 5    7   6   17    1    5   2   57    0    9  ...         0   
...          ...  ...  ..  ...  ...  ...  ..  ...  ...  ...  ...       ...   
5167  Email 5168    2   2    2    3    0   0   32    0    0  ...         0   
5168  Email 5169   35  27   11    2    6   5  151    4    3  ...         0   
5169  Email 5170    0   0    1    1    0   0   11    0    0  ...         0   
5170  Email 5171    2   7    1    0    2   1   28    2    0  ...         0   
5171  Email 5172   22  24    5    1    6   5  148    8    2  ...         0   

      jay  valued  lay  infrastructure  military  allowing  ff  dry  \
0       0       0    0               0         0         0   0    0   
1       0       0    0               0         0         0   1    0   
2       0       0    0               0         0         0   0    0   
3       0       0    0               0         0         0   0    0   
4       0       0    0               0         0         0   1    0   
...   ...     ...  ...             ...       ...       ...  ..  ...   
5167    0       0    0               0         0         0   0    0   
5168    0       0    0               0         0         0   1    0   
5169    0       0    0               0         0         0   0    0   
5170    0       0    0               0         0         0   1    0   
5171    0       0    0               0         0         0   0    0   

      Prediction  
0              0  
1              0  
2              0  
3              0  
4              0  
...          ...  
5167           0  
5168           0  
5169           1  
5170           1  
5171           0  

[5172 rows x 3002 columns]

In [91]:
df.isnull()

Email No.    the     to    ect    and    for     of      a    you  \
0         False  False  False  False  False  False  False  False  False   
1         False  False  False  False  False  False  False  False  False   
2         False  False  False  False  False  False  False  False  False   
3         False  False  False  False  False  False  False  False  False   
4         False  False  False  False  False  False  False  False  False   
...         ...    ...    ...    ...    ...    ...    ...    ...    ...   
5167      False  False  False  False  False  False  False  False  False   
5168      False  False  False  False  False  False  False  False  False   
5169      False  False  False  False  False  False  False  False  False   
5170      False  False  False  False  False  False  False  False  False   
5171      False  False  False  False  False  False  False  False  False   

        hou  ...  connevey    jay  valued    lay  infrastructure  military  \
0     False  ...     False  False   False  False           False     False   
1     False  ...     False  False   False  False           False     False   
2     False  ...     False  False   False  False           False     False   
3     False  ...     False  False   False  False           False     False   
4     False  ...     False  False   False  False           False     False   
...     ...  ...       ...    ...     ...    ...             ...       ...   
5167  False  ...     False  False   False  False           False     False   
5168  False  ...     False  False   False  False           False     False   
5169  False  ...     False  False   False  False           False     False   
5170  False  ...     False  False   False  False           False     False   
5171  False  ...     False  False   False  False           False     False   

      allowing     ff    dry  Prediction  
0        False  False  False       False  
1        False  False  False       False  
2        False  False  False       False  
3        False  False  False       False  
4        False  False  False       False  
...        ...    ...    ...         ...  
5167     False  False  False       False  
5168     False  False  False       False  
5169     False  False  False       False  
5170     False  False  False       False  
5171     False  False  False       False  

[5172 rows x 3002 columns]

In [92]:
df.isnull().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [93]:
df=df.dropna()

In [94]:
df.shape

(5172, 3002)

In [95]:
df.size

15526344

In [96]:
df.ndim

2

In [97]:
df.dtypes

Email No.     object
the            int64
to             int64
ect            int64
and            int64
               ...  
military       int64
allowing       int64
ff             int64
dry            int64
Prediction     int64
Length: 3002, dtype: object

In [98]:
df.columns

Index(['Email No.', 'the', 'to', 'ect', 'and', 'for', 'of', 'a', 'you', 'hou',
       ...
       'connevey', 'jay', 'valued', 'lay', 'infrastructure', 'military',
       'allowing', 'ff', 'dry', 'Prediction'],
      dtype='object', length=3002)

In [99]:
df=df.drop(["Email No."],axis=1)

In [100]:
df.columns

Index(['the', 'to', 'ect', 'and', 'for', 'of', 'a', 'you', 'hou', 'in',
       ...
       'connevey', 'jay', 'valued', 'lay', 'infrastructure', 'military',
       'allowing', 'ff', 'dry', 'Prediction'],
      dtype='object', length=3001)

In [101]:
x=df.drop(["Prediction"],axis=1)
y=df["Prediction"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [102]:
x_train

the  to  ect  and  for  of    a  you  hou  in  ...  enhancements  \
2210    4   4    4    0    2   4   78   14    0  13  ...             0   
4931   17  26    1    5    4   5  100   18    1  17  ...             0   
985     4   0    1    0    5   0   22    0    0   6  ...             0   
4040    2   2    1    2    2   2   42    9    2   6  ...             0   
780    12   6    9    2    2   0   81    6    4  15  ...             0   
...   ...  ..  ...  ...  ...  ..  ...  ...  ...  ..  ...           ...   
3959    0   4    2    0    3   1   36    1    0   4  ...             0   
2388    8   8    2    4    3   3   38    3    0   5  ...             0   
176    22  17    2    9    8   8  163   18    3  41  ...             0   
5044   11  10    7    8    9   3  132   22    1  23  ...             0   
958     0   1    1    2    1   0   21    2    0   0  ...             0   

      connevey  jay  valued  lay  infrastructure  military  allowing  ff  dry  
2210         0    0       0    0               0         0         0   0    0  
4931         0    0       0    0               0         0         0   0    0  
985          0    0       0    0               0         0         0   0    0  
4040         0    0       0    0               0         0         0   0    0  
780          0    0       0    0               0         0         0   0    0  
...        ...  ...     ...  ...             ...       ...       ...  ..  ...  
3959         0    0       0    1               0         0         0   0    0  
2388         0    0       0    0               0         0         0   0    0  
176          0    0       0    0               0         0         0   0    0  
5044         0    0       0    0               0         0         0   0    0  
958          0    0       0    0               0         0         0   0    0  

[3620 rows x 3000 columns]

In [103]:
x_test

the  to  ect  and  for  of    a  you  hou  in  ...  enhancements  \
1359    1   1    1    0    1   0    3    0    0   0  ...             0   
613    16  23    8    6    6   8  119    5    2  18  ...             0   
1557    1   1    1    0    1   0    6    0    0   0  ...             0   
577     5   7    1    2    3   4  130    3    3  18  ...             0   
793     0   1    1    0    0   0    1    0    0   0  ...             0   
...   ...  ..  ...  ...  ...  ..  ...  ...  ...  ..  ...           ...   
2241    0   0    1    0    1   0    1    1    0   0  ...             0   
3016    0   0    1    0    1   0    2    0    0   0  ...             0   
2067    0   0    1    0    1   0    3    0    0   0  ...             0   
547     4   7    2    5    3   0   41    1    0   9  ...             0   
5161   59  30    4   16    9  31  195    0    2  40  ...             0   

      connevey  jay  valued  lay  infrastructure  military  allowing  ff  dry  
1359         0    0       0    0               0         0         0   0    0  
613          0    0       0    0               0         0         0   4    0  
1557         0    0       0    0               0         0         0   0    0  
577          0    0       0    0               0         0         0   1    0  
793          0    0       0    0               0         0         0   0    0  
...        ...  ...     ...  ...             ...       ...       ...  ..  ...  
2241         0    0       0    0               0         0         0   0    0  
3016         0    0       0    0               0         0         0   0    0  
2067         0    0       0    0               0         0         0   0    0  
547          0    0       0    0               0         0         0   0    0  
5161         0    0       0    5               0         0         0   4    0  

[1552 rows x 3000 columns]

In [104]:
y_train

2210    1
4931    0
985     0
4040    1
780     0
       ..
3959    1
2388    0
176     0
5044    0
958     0
Name: Prediction, Length: 3620, dtype: int64

In [105]:
y_test

1359    0
613     0
1557    0
577     1
793     1
       ..
2241    1
3016    0
2067    0
547     0
5161    0
Name: Prediction, Length: 1552, dtype: int64

In [106]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [107]:
y_pred_knn=knn.predict(x_test)
y_pred_knn

array([0, 0, 0, ..., 0, 0, 1])

In [108]:
print("Confusion Matrix :")
print(confusion_matrix(y_test,y_pred_knn))
print("Classification Report :")
print(classification_report(y_test,y_pred_knn))

Confusion Matrix :
[[950 126]
 [ 89 387]]
Classification Report :
              precision    recall  f1-score   support

           0       0.91      0.88      0.90      1076
           1       0.75      0.81      0.78       476

    accuracy                           0.86      1552
   macro avg       0.83      0.85      0.84      1552
weighted avg       0.87      0.86      0.86      1552



In [109]:
svm=SVC(kernel="linear",probability=True)
svm.fit(x_train,y_train)

SVC(kernel='linear', probability=True)

In [110]:
y_pred_svm=svm.predict(x_test)
y_pred

array([0, 1, 0, ..., 1, 0, 0])

In [111]:
print("Confusion Matrix :")
print(confusion_matrix(y_test,y_pred_svm))
print("Classification Report :")
print(classification_report(y_test,y_pred_svm))

Confusion Matrix :
[[1039   37]
 [  32  444]]
Classification Report :
              precision    recall  f1-score   support

           0       0.97      0.97      0.97      1076
           1       0.92      0.93      0.93       476

    accuracy                           0.96      1552
   macro avg       0.95      0.95      0.95      1552
weighted avg       0.96      0.96      0.96      1552

